# Generated by Django 5.2.11 on 2026-02-11 22:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brinco', models.CharField(max_length=50, unique=True, verbose_name='Número do Brinco')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome (Opcional)')),
                ('raca', models.CharField(choices=[('NELORE', 'Nelore'), ('ANGUS', 'Angus'), ('BRAHMAN', 'Brahman'), ('GIROLANDO', 'Girolando'), ('HOLANDES', 'Holandês'), ('OUTRA', 'Outra')], default='NELORE', max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso Atual (kg)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('qrcode_img', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
    ]
