# Generated by Django 5.2.11 on 2026-02-20 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bovinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boi',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo no Pasto'), ('VENDIDO', 'Vendido'), ('MORTO', 'Morto')], default='ATIVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='boi',
            name='brinco',
            field=models.CharField(max_length=50, verbose_name='Número do Brinco'),
        ),
        migrations.CreateModel(
            name='HistoricoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_pesagem', models.DateTimeField(auto_now_add=True)),
                ('boi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_peso', to='bovinos.boi')),
            ],
            options={
                'ordering': ['-data_pesagem'],
            },
        ),
    ]
